export const SERVICES = [
  {
    id: 'emergency-towing',
    title: 'Emergency Towing',
    iconName: 'Siren',
    description: 'Fast response for accidents and breakdowns. We\'ll get your vehicle to a repairer or your home quickly and safely.',
    content: 'Our emergency towing service is available 24/7 across Brisbane. We understand that being stranded is stressful, which is why we prioritize rapid response times and professional care.'
  },
  {
    id: 'car-transport',
    title: 'Car Transport',
    iconName: 'Car',
    description: 'Professional transport for luxury, classic, or non-running vehicles across Brisbane and South East Queensland.',
    content: 'Whether you\'re moving a classic car to a show or a luxury vehicle to a new home, our specialized transport solutions ensure your pride and joy arrives in perfect condition.'
  },
  {
    id: 'roadside-assistance',
    title: 'Roadside Assistance',
    iconName: 'Wrench',
    description: 'Jump starts, tire changes, and fuel delivery. Sometimes you don\'t need a tow, just a helping hand.',
    content: 'Flat battery? Empty tank? Our roadside assistance team can often get you back on the road without needing a tow, saving you time and money.'
  },
  {
    id: 'accident-recovery',
    title: 'Accident Recovery',
    iconName: 'ShieldCheck',
    description: 'We work with all major insurance companies to provide seamless accident recovery and storage.',
    content: 'In the unfortunate event of an accident, we handle everything from the initial recovery to secure storage and coordination with your insurance provider.'
  },
  {
    id: 'machinery-transport',
    title: 'Machinery Transport',
    iconName: 'Construction',
    description: 'From motorcycles to light commercial trucks and machinery, we have the equipment to handle it all.',
    content: 'Our heavy-duty tilt trays are capable of transporting a wide range of machinery, including forklifts, excavators, and light commercial vehicles.'
  },
  {
    id: 'container-towing',
    title: 'Container Towing',
    iconName: 'Box',
    description: 'Specialized shipping container transport and positioning for 10ft and 20ft containers.',
    content: 'Need to move a shipping container? We specialize in the transport and precise placement of 10ft and 20ft containers across Brisbane. Whether it\'s for site storage, a tiny home project, or commercial use, our tilt-tray trucks make the process effortless.'
  },
  {
    id: 'motorhome-towing',
    title: 'Motorhome Towing',
    iconName: 'Home',
    description: 'Safe and secure towing for motorhomes and large RVs. We handle oversized vehicles with care.',
    content: 'Motorhomes require specialized handling due to their size and weight. Our fleet includes heavy-duty tow trucks equipped to transport large RVs and motorhomes safely, ensuring they reach their destination without a scratch.'
  },
  {
    id: 'caravan-towing',
    title: 'Caravan Towing',
    iconName: 'Tent',
    description: 'Professional transport for caravans and trailers of all sizes across Brisbane.',
    content: 'Whether you\'re heading for a holiday or moving your caravan to storage, we provide reliable transport. We ensure all connections are secure and your valuable assets are transported with the utmost professional care.'
  },
  {
    id: 'boat-towing',
    title: 'Boat Towing',
    iconName: 'Anchor',
    description: 'Safe and secure boat transport for vessels on trailers to any destination.',
    content: 'Moving your boat to a new berth or taking it in for service? We specialize in boat towing, ensuring your vessel is handled with care and reaches its destination safely.'
  }
];

export const SUBURBS = [
  { id: 'brisbane', name: 'Brisbane', region: 'Greater Brisbane' },
  { id: 'gold-coast', name: 'Gold Coast', region: 'South East QLD' },
  { id: 'queensland', name: 'Queensland', region: 'Statewide' },
  { id: 'sunshine-coast', name: 'Sunshine Coast', region: 'South East QLD' },
  { id: 'redcliffe', name: 'Redcliffe', region: 'North' },
  { id: 'logan', name: 'Logan', region: 'Greater South' },
  { id: 'ipswich', name: 'Ipswich', region: 'Greater West' },
  { id: 'caboolture', name: 'Caboolture', region: 'North' },
  { id: 'beenleigh', name: 'Beenleigh', region: 'South' },
  { id: 'brisbane-north', name: 'Brisbane North', region: 'North' },
  { id: 'brisbane-south', name: 'Brisbane South', region: 'South' },
  { id: 'brisbane-west', name: 'Brisbane West', region: 'West' },
  { id: 'capalaba', name: 'Capalaba', region: 'East' },
  { id: 'cleveland', name: 'Cleveland', region: 'East' },
  { id: 'fairfield', name: 'Fairfield', region: 'South' },
  { id: 'hamilton', name: 'Hamilton', region: 'Central' },
  { id: 'mansfield', name: 'Mansfield', region: 'South' },
  { id: 'milton', name: 'Milton', region: 'Central' },
  { id: 'salisbury', name: 'Salisbury', region: 'South' },
  { id: 'seven-hills', name: 'Seven Hills', region: 'East' },
  { id: 'springfield', name: 'Towing in Springfield', region: 'Greater West' },
  { id: 'stafford', name: 'Stafford', region: 'North' },
  { id: 'wynnum', name: 'Wynnum', region: 'East' },
  { id: 'brisbane-cbd', name: 'Brisbane CBD', region: 'Central' },
  { id: 'fortitude-valley', name: 'Fortitude Valley', region: 'Central' },
  { id: 'south-brisbane', name: 'South Brisbane', region: 'Central' },
  { id: 'chermside', name: 'Chermside', region: 'North' },
  { id: 'north-lakes', name: 'North Lakes', region: 'North' },
  { id: 'indooroopilly', name: 'Indooroopilly', region: 'West' },
  { id: 'sunnybank', name: 'Sunnybank', region: 'South' },
  { id: 'carindale', name: 'Carindale', region: 'East' },
  { id: 'brisbane-southside', name: 'Brisbane Southside', region: 'South' },
  { id: 'browns-plains', name: 'Browns Plains', region: 'Greater South' },
  { id: 'morningside', name: 'Morningside', region: 'East' },
  { id: 'eight-mile-plains', name: 'Eight Mile Plains', region: 'South' },
  { id: 'rochedale', name: 'Rochedale', region: 'South' },
  { id: 'underwood', name: 'Underwood', region: 'South' },
  { id: 'runcorn', name: 'Runcorn', region: 'South' },
  { id: 'coopers-plains', name: 'Coopers Plains', region: 'South' },
  { id: 'mt-gravatt', name: 'Mt Gravatt', region: 'South' },
  { id: 'tarragindi', name: 'Tarragindi', region: 'South' },
  { id: 'holland-park', name: 'Holland Park', region: 'South' },
  { id: 'greenslopes', name: 'Greenslopes', region: 'South' },
  { id: 'moorooka', name: 'Moorooka', region: 'South' },
  { id: 'rocklea', name: 'Rocklea', region: 'South' },
  { id: 'archerfield', name: 'Archerfield', region: 'South' }
];

export const PHONE_NUMBER = "0499 600 300";
export const PHONE_LINK = "tel:0499600300";

export const GITHUB_IMAGE_BASE = "https://raw.githubusercontent.com/udes77/TTB/main/";

export const GALLERY_IMAGES = [
  "Tow-trucks-brisbane1.jpg",
  "Tow-trucks-brisbane2.jpg",
  "Tow-trucks-brisbane3.jpg",
  "Tow-trucks-brisbane4.jpg",
  "Tow-trucks-brisbane5.jpg",
  "Tow-trucks-brisbane6.jpg",
  "Tow-trucks-brisbane7.jpg",
  "Tow-trucks-brisbane8.jpg",
  "Tow-trucks-brisbane9.jpg",
  "Tow-trucks-brisbane10.jpg",
  "Tow-trucks-brisbane11.jpg",
  "Tow-trucks-brisbane12.jpg",
  "Tow-trucks-brisbane13.jpg",
  "Tow-trucks-brisbane14.jpg",
  "Tow-trucks-brisbane15.jpg",
  "Tow-trucks-brisbane16.jpg",
  "Tow-trucks-brisbane17.jpg",
  "Tow-trucks-brisbane18.jpg",
  "Tow-trucks-brisbane19.jpg",
  "Tow-trucks-brisbane20.jpg",
  "Tow-trucks-brisbane21.jpg",
  "Tow-trucks-brisbane22.jpg",
  "Tow-trucks-brisbane23.jpg",
  "Tow-trucks-brisbane24.jpg",
  "Tow-trucks-brisbane25.jpg",
  "Tow-trucks-brisbane26.jpg",
  "Tow-trucks-brisbane27.jpg",
  "Tow-trucks-brisbane28.jpg",
  "Tow-trucks-brisbane71.jpg",
  "Tow-trucks-brisbane72.jpg",
  "Tow-trucks-brisbane73.jpg",
  "Tow-trucks-brisbane74.jpg",
  "Tow-trucks-brisbane75.jpg",
  "Tow-trucks-brisbane76.jpg",
  "Tow-trucks-brisbane77.jpg",
  "IMG_0315.JPG",
  "IMG_0397.JPG",
  "IMG_0598.JPG",
  "IMG_0784.JPG",
  "IMG_0853.JPG",
  "IMG_0963.JPG",
  "IMG_1203.JPG",
  "IMG_1211.JPG",
  "IMG_1373.JPG",
  "IMG_1438.JPG",
  "IMG_1758.JPG",
  "IMG_1762.JPG",
  "IMG_1804.JPG",
  "IMG_1806.JPG",
  "IMG_1848.JPG",
  "IMG_1873.JPG",
  "IMG_1883.JPG",
  "IMG_1898.JPG",
  "IMG_1929.JPG",
  "IMG_1966.JPG",
  "IMG_1973.JPG",
  "IMG_1977.JPG",
  "IMG_1978.JPG",
  "IMG_2275.JPG",
  "IMG_2595.JPG",
  "IMG_2596.JPG",
  "IMG_2598.JPG",
  "IMG_2609.JPG",
  "IMG_2610.JPG",
  "IMG_2615.JPG",
  "IMG_2619.JPG",
  "IMG_3195.JPG",
  "IMG_3348.JPG",
  "IMG_3539.JPG",
  "IMG_3547.JPG",
  "IMG_3771.JPG",
  "IMG_3854.JPG",
  "IMG_3857.JPG",
  "IMG_3919.JPG",
  "IMG_4274.JPG",
  "IMG_4336.JPG",
  "IMG_4413.JPG",
  "IMG_4720.JPG",
  "IMG_4887.JPG",
  "IMG_4893.JPG",
  "IMG_5082.JPG",
  "IMG_5525.JPG",
  "IMG_5542.JPG",
  "IMG_5590.JPG",
  "IMG_5662.JPG",
  "IMG_5719.JPG",
  "IMG_6198.JPG",
  "IMG_6295.JPG",
  "IMG_6311.JPG",
  "IMG_6313.JPG",
  "IMG_6318.JPG",
  "IMG_6398.JPG",
  "IMG_7513.JPG",
  "IADH5332.JPG",
  "IIFN1158.JPG",
  "NNWW1807.JPG",
  "PMCX6791.JPG",
  "QPDJ5520.JPG",
  "SVGJ4053.JPG",
  "TFPN1700.JPG"
];
